// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriVie.Models.data;

#nullable disable

namespace NutriVie.Migrations
{
    [DbContext(typeof(NutriVieDbContext))]
    [Migration("20260923153558_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriVie.Models.Service", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Description = "Des recettes équilibrées et faciles à préparer pour toute la famille.",
                            Nom = "Recettes Saines"
                        },
                        new
                        {
                            id = 2,
                            Description = "Des plans alimentaires personnalisés par nos nutritionnistes.",
                            Nom = "Plans Nutritionnels"
                        },
                        new
                        {
                            id = 3,
                            Description = "Des articles et guides sur la nutrition et le bien-être.",
                            Nom = "Conseils d'Experts"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
