// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriVie.Models.data;

#nullable disable

namespace NutriVie.Migrations
{
    [DbContext(typeof(NutriVieDbContext))]
    [Migration("20260923161819_Seed1")]
    partial class Seed1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriVie.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Française"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Indienne"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Africaine"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Italienne"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Orientale"
                        });
                });

            modelBuilder.Entity("NutriVie.Models.Recette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TempsCuisson")
                        .HasColumnType("int");

                    b.Property<int>("TempsPreparation")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Recette");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategorieId = 1,
                            Description = "Ragoût traditionnel français au boeuf et vin rouge.",
                            Image = "Boeuf_bourguignon.jpg",
                            Nom = "Boeuf bourguignon",
                            TempsCuisson = 180,
                            TempsPreparation = 30
                        },
                        new
                        {
                            Id = 2,
                            CategorieId = 1,
                            Description = "Tarte salée avec bacon, oeufs et fromage.",
                            Image = "Quiche_loraine.jpg",
                            Nom = "Quiche lorraine",
                            TempsCuisson = 45,
                            TempsPreparation = 20
                        },
                        new
                        {
                            Id = 3,
                            CategorieId = 2,
                            Description = "Poulet mariné dans une sauce crémeuse épicée.",
                            Image = "Poulet_tikka_masala.jpg",
                            Nom = "Poulet tikka masala",
                            TempsCuisson = 35,
                            TempsPreparation = 40
                        },
                        new
                        {
                            Id = 4,
                            CategorieId = 2,
                            Description = "Poulet tendre dans une sauce tomate et beurre.",
                            Image = "Poulet_au_beurre.jpg",
                            Nom = "Poulet au beurre",
                            TempsCuisson = 40,
                            TempsPreparation = 25
                        },
                        new
                        {
                            Id = 5,
                            CategorieId = 3,
                            Description = "Poulet mariné au citron et aux oignons.",
                            Image = "Poulet_Yassa.jpg",
                            Nom = "Poulet yassa",
                            TempsCuisson = 50,
                            TempsPreparation = 35
                        },
                        new
                        {
                            Id = 6,
                            CategorieId = 3,
                            Description = "accompagnement traditionnel en Afrique du Sud.",
                            Image = "Riz_jaune.jpg",
                            Nom = "Riz jaune",
                            TempsCuisson = 25,
                            TempsPreparation = 10
                        },
                        new
                        {
                            Id = 7,
                            CategorieId = 4,
                            Description = "Pâtes gratinées avec viande et sauce tomate.",
                            Image = "Lasagne.jpg",
                            Nom = "Lasagne",
                            TempsCuisson = 60,
                            TempsPreparation = 45
                        },
                        new
                        {
                            Id = 8,
                            CategorieId = 4,
                            Description = "Riz crémeux italien aux champignons.",
                            Image = "Risotto_Champignons.jpg",
                            Nom = "Risotto aux champignons",
                            TempsCuisson = 35,
                            TempsPreparation = 15
                        },
                        new
                        {
                            Id = 9,
                            CategorieId = 5,
                            Description = "Semoule servie avec légumes et viandes variées.",
                            Image = "Couscous_royal.jpg",
                            Nom = "Couscous yoyal",
                            TempsCuisson = 90,
                            TempsPreparation = 40
                        },
                        new
                        {
                            Id = 10,
                            CategorieId = 5,
                            Description = "Viande marinée grillée servie dans un pain pita.",
                            Image = "Shawarma.jpg",
                            Nom = "Shawarma",
                            TempsCuisson = 30,
                            TempsPreparation = 25
                        });
                });

            modelBuilder.Entity("NutriVie.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Des recettes équilibrées et faciles à préparer pour toute la famille.",
                            Nom = "Recettes Saines"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Des plans alimentaires personnalisés par nos nutritionnistes.",
                            Nom = "Plans Nutritionnels"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Des articles et guides sur la nutrition et le bien-être.",
                            Nom = "Conseils d'Experts"
                        });
                });

            modelBuilder.Entity("NutriVie.Models.Recette", b =>
                {
                    b.HasOne("NutriVie.Models.Categorie", "categorie")
                        .WithMany()
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categorie");
                });
#pragma warning restore 612, 618
        }
    }
}
